services:
  db:
    image: ankane/pgvector:latest
    container_name: polar
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data3:/var/lib/postgresql/data
      - /home/faraji/Developer/Learning/services/data:/var/lib/postgresql/pg/data/
    environment:
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - polarbear

volumes:
  db-data3:
secrets:
  db-password:
    file: db/password.txt

networks:
  polarbear:
