# Generated by Django 5.0.6 on 2024-07-01 06:56

from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        VectorExtension()
    ]
