# Generated by Django 5.0.6 on 2024-07-01 08:14

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_book_category'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embeddings'], m=16, name='embeddings_index', opclasses=['vector_cosine_ops']),
        ),
    ]
